[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.14"
name = "anki-card-tooling"
dynamic = ["version"]
dependencies = [
    "ruff==0.14.10",
    "pydantic==2.12.5",
]


[tool.setuptools]
packages = []
py-modules = []